<Workspace Version="1.2.1.3083" X="-527.218312994045" Y="401.514765113719" zoom="0.599637469638882" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="BoundingBox.Max" resolvedName="Autodesk.DesignScript.Geometry.BoundingBox" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="BoundingBox.Min" resolvedName="Autodesk.DesignScript.Geometry.BoundingBox" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="de398f19-9dda-4448-b260-d97475bc1588" type="PythonNodeModels.PythonNode" nickname="DynamicSectionView:Python Script" x="1533.50905180414" y="96.65780739177" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="5">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import FilteredElementCollector as _FilteredElementCollector
from Autodesk.Revit.DB import ViewFamilyType as _ViewFamilyType

import System
from System import Array
from System.Collections.Generic import *
import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")
import os
import math
import shutil


def clean_up(folder_name):
	for file_name in os.listdir(folder_name): # delete all content
		file_path = os.path.join(folder_name, file_name)
		
		if os.path.isfile(file_path):
			os.remove(file_path)
		else:
			shutil.rmtree(file_path)
	os.makedirs(os.path.join(folder_name, "origin")) # add origin folder


def get_ViewFamilyTypeId(viewFamilyTypeName):	
	names = []
	ids = []
	viewFamilyTypeId = -1
	collector = _FilteredElementCollector(doc).OfClass(_ViewFamilyType) #collecting all elements of type ViewFamilyType
	for t in collector:
		names.append(t.FamilyName)
		ids.append(t.Id)
		if t.FamilyName == viewFamilyTypeName:
			viewFamilyTypeId = t.Id
			break # get the first
	return viewFamilyTypeId
			
			
def create_view(doc, viewFamilyTypeId, boundingBox, voxel_size):		
	if viewFamilyTypeId != -1:
		TransactionManager.Instance.EnsureInTransaction(doc)
		
		boundingBoxSlice = boundingBox
		boundingBoxSlice.Max = XYZ(boundingBox.Max.X, boundingBox.Max.Y, boundingBox.Min.Z + voxel_size)  # adjust boundingbox for far clip offset		
		sectionView = ViewSection.CreateDetail(doc, viewFamilyTypeId, boundingBoxSlice) 					
		
		viewId = Autodesk.Revit.DB.ElementId(int(str(sectionView.Id)) - 1)
		minY = boundingBoxSlice.Min.Y
		maxY = boundingBoxSlice.Max.Y
		midY = (maxY + minY) / 2
		minX = boundingBoxSlice.Min.X
		maxX = boundingBoxSlice.Max.X
		minZ = boundingBoxSlice.Min.Z
		axis = Line.CreateBound(XYZ(minX, midY, minZ), XYZ(maxX, midY, minZ))  # flip DetailView direction
		ElementTransformUtils.RotateElement(doc, viewId, axis, math.pi)	
		
		TransactionManager.Instance.TransactionTaskDone()
		return sectionView


def update_view(doc, view, voxel_size):
	TransactionManager.Instance.EnsureInTransaction(doc)	
	translationVec = XYZ(0, 0, voxel_size)
	viewId = Autodesk.Revit.DB.ElementId(int(str(view.Id)) - 1)
	ElementTransformUtils.MoveElement(doc, viewId, translationVec)	
	TransactionManager.Instance.TransactionTaskDone()
	return sectionView, height
	
	
def export_view_image(view, path, image_width, doc):
	TransactionManager.Instance.EnsureInTransaction(doc)
	ieo = ImageExportOptions()
	ieo.ExportRange = ExportRange.SetOfViews
	ieo.SetViewsAndSheets([view.Id])
	ieo.FilePath = path	
	ieo.HLRandWFViewsFileType = ImageFileType.PNG
	ieo.ShadowViewsFileType = ImageFileType.PNG
	ieo.PixelSize = image_width
	doc.ExportImage(ieo)
	TransactionManager.Instance.TransactionTaskDone()
	return ieo.IsValidFileName(path)
	
	
def delete_views(doc, views):
	TransactionManager.Instance.EnsureInTransaction(doc)	
	for view in views:
		doc.Delete(view.Id)
	TransactionManager.Instance.TransactionTaskDone()


def apply_viewTemplate(doc, view, viewTemplateName):
	viewTemplate = None
	collector = FilteredElementCollector(doc).OfClass(View)
	for i in collector:
		if i.IsTemplate == True and i.Name == viewTemplateName:
			viewTemplate = i
	
	TransactionManager.Instance.EnsureInTransaction(doc)
	if viewTemplate is not None:
		view.ViewTemplateId = viewTemplate.Id
	TransactionManager.Instance.TransactionTaskDone()


def get_scopeBox(name):
	collector = FilteredElementCollector(doc)
	elements = collector.OfCategory(BuiltInCategory.OST_VolumeOfInterest).ToElements()
	for element in elements:
		if element.Name == name:
			return element


def rename_images(digit, folder_name):
	path = os.path.join(folder_name, "origin")
	new_filenames = []
	
	for f_name in os.listdir(path):
	    new_f_name = f_name[0:digit] +'.png'  # 3 digits worth
	    os.rename(os.path.join(path, f_name), os.path.join(path, new_f_name))
	    new_filenames.append(new_f_name)
	    

filePath = IN[0]
slices = IN[1] * 12
scopeBox_name = IN[2]
viewTemplateName = IN[3]
is_delete = IN[4]

clean_up(filePath)

doc = DocumentManager.Instance.CurrentDBDocument
scopeBox = get_scopeBox(scopeBox_name)

filenames = []

try:
	count = 1
	heights = []
	
	viewFamilyTypeId = get_ViewFamilyTypeId("Detail View")
	boundingBox = scopeBox.get_BoundingBox(None) # https://github.com/DynamoDS/DynamoRevit/blob/Revit2015/src/Libraries/RevitNodes/Elements/Element.cs
	
	voxel_size = (boundingBox.Max.Z - boundingBox.Min.Z) / slices * 12 # feet to inch
	image_width = (boundingBox.Max.X - boundingBox.Min.X) / voxel_size
		
	if image_width &lt;= 15000:
		bottom = boundingBox.Min.Z
		top = boundingBox.Max.Z
		height = bottom
		digit = len(str(int((top - bottom) / voxel_size))) 	
		
		sectionView = create_view(doc, viewFamilyTypeId, boundingBox, voxel_size)
		apply_viewTemplate(doc, sectionView, viewTemplateName)
		
		while height &lt; top:
			if count &gt; 10:  # TEMP for test
				break
		
			heights.append(height)
		
			height += voxel_size	
			update_view(doc, sectionView, voxel_size)
			
			imageName = filePath + "\\origin\\" + str(count).rjust(digit, '0') # filename format: "tempFileName - view type - view name"; craete origin folder
			isValid = export_view_image(sectionView, imageName, image_width, doc)
			
			filenames.append(imageName)
			filenames.append(isValid)
			
			count += 1
			
		if is_delete:
			delete_views(doc, [sectionView])
			
		TransactionManager.Instance.ForceCloseTransaction()  # Dynamo transaction force close order
			
		rename_images(digit, filePath)
			
		OUT = "success", digit, sectionView, image_width, str(voxel_size * 12) + " in" # other outputs:  boundingBox.Min, boundingBox.Max, heights
	else:
		OUT = "failed: image_width out of range &gt; 15000, please set larger # of slices", image_width
except Exception as e:
	OUT =  "failed", e</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d5c1fe87-270a-4c1b-9e06-f0552677a491" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1043.93377584472" y="7.65171045363002" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;C:\\Dynamo\\revit-3d-print\\image&quot;;&#xA;560;&#xA;&quot;3D Print&quot;;&#xA;&quot;3d Print&quot;;&#xA;false;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="11674bed-bf3e-4a7f-98e0-4aa48b365eb2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1791.64392306725" y="101.181241193622" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="48c66b7a-d765-4c31-af97-2588749ed5d1" type="PythonNodeModels.PythonNode" nickname="Invert Images:Python Script" x="2306.65143464366" y="-9.41401249005767" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="7">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
      <PortInfo index="6" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import FilteredElementCollector as _FilteredElementCollector
from Autodesk.Revit.DB import ViewFamilyType as _ViewFamilyType

import System
from System import Array
from System.Collections.Generic import *
import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")
import os

image_path = IN[0].replace("\\", "\\\\")
digits = IN[1]
voxel_size = IN[2]
scale = IN[3]
script_path = IN[4]
border = IN[5]
log_path = IN[6]

inch2meter = 0.0254
voxel_size_parameter = voxel_size * scale * inch2meter

command = "python " + script_path + " \"" + image_path + "\\\\\" " + str(digits) + " " + str(voxel_size_parameter) + " " + border + " &gt; " + log_path
os.system(command)
OUT = command</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.StringInput guid="cff46afc-49a1-4f5b-87c3-7284573648f0" type="CoreNodeModels.Input.StringInput" nickname="String: external python script path" x="1955.51166626706" y="297.598312799404" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>C:\Dynamo\revit-3d-print\script\process_images.py</System.String>
      <System.String value="C:\Dynamo\revit-3d-print\script\process_images.py" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.StringInput guid="c49fa72e-2b49-4831-b54a-6bde39404b72" type="CoreNodeModels.Input.StringInput" nickname="String: log path" x="2047.72682447602" y="445.956222667298" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>C:\voxelptint.txt</System.String>
      <System.String value="C:\voxelptint.txt" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.StringInput guid="7f599b7b-f639-4918-a5b3-dc3d7b3476d0" type="CoreNodeModels.Input.StringInput" nickname="String: border" x="2070.94296794615" y="378.248204387795" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>5</System.String>
      <System.String value="5" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="a36f99b2-413e-4d98-8fd7-ccd8358ec16d" type="PythonNodeModels.PythonNode" nickname="Slice Height (inch):Python Script" x="1556.13441021393" y="-164.323070008839" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import FilteredElementCollector as _FilteredElementCollector
from Autodesk.Revit.DB import ViewFamilyType as _ViewFamilyType

import System
from System import Array
from System.Collections.Generic import *
import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")
import os
import math
import shutil
			
def get_scopeBox(name):
	collector = FilteredElementCollector(doc)
	elements = collector.OfCategory(BuiltInCategory.OST_VolumeOfInterest).ToElements()
	for element in elements:
		if element.Name == name:
			return element

slice = IN[0]
scopeBox_name = IN[1]

doc = DocumentManager.Instance.CurrentDBDocument
scopeBox = get_scopeBox(scopeBox_name)
boundingBox = scopeBox.get_BoundingBox(None) # https://github.com/DynamoDS/DynamoRevit/blob/Revit2015/src/Libraries/RevitNodes/Elements/Element.cs
voxel_size = (boundingBox.Max.Z - boundingBox.Min.Z) * 12 / slice  # boundingBox size in feet
				
OUT = voxel_size
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0f93f4a3-141e-4cf0-954e-02c991396921" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="model scale / real scale (inch)" x="1981.67009937872" y="210.843990685324" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="(1 / 16) / 1;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="de398f19-9dda-4448-b260-d97475bc1588" start_index="0" end="11674bed-bf3e-4a7f-98e0-4aa48b365eb2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="0" end="de398f19-9dda-4448-b260-d97475bc1588" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="0" end="48c66b7a-d765-4c31-af97-2588749ed5d1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="1" end="de398f19-9dda-4448-b260-d97475bc1588" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="1" end="a36f99b2-413e-4d98-8fd7-ccd8358ec16d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="2" end="de398f19-9dda-4448-b260-d97475bc1588" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="2" end="a36f99b2-413e-4d98-8fd7-ccd8358ec16d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="3" end="de398f19-9dda-4448-b260-d97475bc1588" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="4" end="de398f19-9dda-4448-b260-d97475bc1588" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="11674bed-bf3e-4a7f-98e0-4aa48b365eb2" start_index="0" end="48c66b7a-d765-4c31-af97-2588749ed5d1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cff46afc-49a1-4f5b-87c3-7284573648f0" start_index="0" end="48c66b7a-d765-4c31-af97-2588749ed5d1" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c49fa72e-2b49-4831-b54a-6bde39404b72" start_index="0" end="48c66b7a-d765-4c31-af97-2588749ed5d1" end_index="6" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7f599b7b-f639-4918-a5b3-dc3d7b3476d0" start_index="0" end="48c66b7a-d765-4c31-af97-2588749ed5d1" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a36f99b2-413e-4d98-8fd7-ccd8358ec16d" start_index="0" end="48c66b7a-d765-4c31-af97-2588749ed5d1" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0f93f4a3-141e-4cf0-954e-02c991396921" start_index="0" end="48c66b7a-d765-4c31-af97-2588749ed5d1" end_index="3" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="1f7ed75c-d75a-48b6-ad1d-3087eb4cd3ec" text="para1: image export directory&#xD;&#xA;para2: slices&#xD;&#xA;para3: ScopeBox name&#xD;&#xA;para4: ViewTemplate name&#xD;&#xA;para5: delete temporary DetailView afterward" x="1048.28943880828" y="-103.68543284518" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="b0d6e6dc-b093-4f22-b8dd-2d4a9bb5c92a" annotationText="input 1" left="1033.93377584472" top="-133.68543284518" width="349" height="298.33714329881" fontSize="14" InitialTop="-103.68543284518" InitialHeight="312.983639261595" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="d5c1fe87-270a-4c1b-9e06-f0552677a491" />
      <Models ModelGuid="1f7ed75c-d75a-48b6-ad1d-3087eb4cd3ec" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="abf39d85-f686-4d86-8146-ed7d23e8ce02" annotationText="input 2" left="1945.51166626706" top="180.843990685324" width="227.43130167909" height="333.112231981974" fontSize="14" InitialTop="210.843990685324" InitialHeight="238.616419512883" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="cff46afc-49a1-4f5b-87c3-7284573648f0" />
      <Models ModelGuid="c49fa72e-2b49-4831-b54a-6bde39404b72" />
      <Models ModelGuid="7f599b7b-f639-4918-a5b3-dc3d7b3476d0" />
      <Models ModelGuid="0f93f4a3-141e-4cf0-954e-02c991396921" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>
