<Workspace Version="1.2.1.3083" X="117.196313336185" Y="7.70733802463707" zoom="0.948768827037611" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e2251d0b-dcd0-4006-92b5-1801c4c04f95" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.ActiveView" x="132.960024702515" y="165.826076577797" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.ActiveView">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="2e58ce89-a9b7-4275-b00d-4a84480de551" type="PythonNodeModels.PythonNode" nickname="Python Script" x="425.269036934351" y="201.710179824463" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="7">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />  
      <PortInfo index="6" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

import System
from System import Array
from System.Collections.Generic import *

import sys

view = UnwrapElement(IN[0])
filePath = IN[1]
direction = IN[2]

bottom = IN[3]
top = IN[4]
voxel_size = IN[5]
depth = IN[6]
doc = DocumentManager.Instance.CurrentDBDocument


def setCutBottomPlane(height, depth, direction):  # convert inch to foot	
	viewRange = view.GetViewRange()
	if direction == 'cut-bottom':
		viewRange.SetOffset(PlanViewPlane.CutPlane, height / 12)
		viewRange.SetOffset(PlanViewPlane.BottomClipPlane, (height - depth) / 12)
		viewRange.SetOffset(PlanViewPlane.ViewDepthPlane, (height - depth) / 12)
		view.SetViewRange(viewRange)
	elif direction == 'top-cut':
		viewRange.SetOffset(PlanViewPlane.TopClipPlane, height / 12.0)
		viewRange.SetOffset(PlanViewPlane.CutPlane, (height - depth) / 12.0)
		viewRange.SetOffset(PlanViewPlane.BottomClipPlane, -12 / 12)
		viewRange.SetOffset(PlanViewPlane.ViewDepthPlane, -12 / 12)
		view.SetViewRange(viewRange)


def exportViewImage(path, pixel_size):
	ieo = ImageExportOptions()
	ieo.FilePath = path	
	ieo.HLRandWFViewsFileType = ImageFileType.PNG
	ieo.ShadowViewsFileType = ImageFileType.PNG
	ieo.PixelSize = pixel_size
	doc.ExportImage(ieo)
	

bbox = view.CropBox
pixel_size = (bbox.Max.X - bbox.Min.X) * 12 * voxel_size
try:
	pre_i = 0 # slow issue: delete the first picture
	pre_j = 0
	count = -1
	transaction = Transaction(doc, 'transaction123')
	digit = len(str(int((top - bottom) / voxel_size)))
	
	height = bottom
	while height &lt; top:
		height += voxel_size
		transaction.Start()
		setCutBottomPlane(height, depth, direction)
		imageName = filePath + str(count).rjust(digit)
		exportViewImage(imageName, pixel_size)
		
		transaction.Commit()
		count += 1
			
	OUT = "succeed"
except Exception as e:
	OUT =  e
	
TransactionManager.Instance.TransactionTaskDone()
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5499e6b9-fad4-478b-8aa7-ca42f3e074c3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.Current" x="-14.7559654164786" y="160.002091399306" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.Current" />
    <CoreNodeModels.Input.StringInput guid="8b005680-9ee3-408e-b3b7-70168362ff3b" type="CoreNodeModels.Input.StringInput" nickname="String" x="115.142496455285" y="262.856491853958" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>C:\Dynamo\ViewRange\test_views\slice</System.String>
      <System.String value="C:\Dynamo\ViewRange\test_views\slice" />
    </CoreNodeModels.Input.StringInput>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="56dd9eab-9080-420a-9880-6ea5b064e943" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="195.591593313404" y="438.326856278979" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="-1 * 12;&#xA;50 * 12;&#xA;0.9;&#xA;1;" ShouldFocus="false" />
    <CoreNodeModels.Input.StringInput guid="d47d82c7-945b-44f4-9dc5-5b3636052184" type="CoreNodeModels.Input.StringInput" nickname="String" x="253.174092380138" y="342.436063155439" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>top-cut</System.String>
      <System.String value="top-cut" />
    </CoreNodeModels.Input.StringInput>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e2251d0b-dcd0-4006-92b5-1801c4c04f95" start_index="0" end="2e58ce89-a9b7-4275-b00d-4a84480de551" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5499e6b9-fad4-478b-8aa7-ca42f3e074c3" start_index="0" end="e2251d0b-dcd0-4006-92b5-1801c4c04f95" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8b005680-9ee3-408e-b3b7-70168362ff3b" start_index="0" end="2e58ce89-a9b7-4275-b00d-4a84480de551" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56dd9eab-9080-420a-9880-6ea5b064e943" start_index="0" end="2e58ce89-a9b7-4275-b00d-4a84480de551" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56dd9eab-9080-420a-9880-6ea5b064e943" start_index="1" end="2e58ce89-a9b7-4275-b00d-4a84480de551" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56dd9eab-9080-420a-9880-6ea5b064e943" start_index="2" end="2e58ce89-a9b7-4275-b00d-4a84480de551" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56dd9eab-9080-420a-9880-6ea5b064e943" start_index="3" end="2e58ce89-a9b7-4275-b00d-4a84480de551" end_index="6" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d47d82c7-945b-44f4-9dc5-5b3636052184" start_index="0" end="2e58ce89-a9b7-4275-b00d-4a84480de551" end_index="2" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="d0dbc237-90c9-4094-b06f-46eda4c01152" text="bottom height (in inch)&#xD;&#xA;top height&#xD;&#xA;voxel size&#xD;&#xA;view range height" x="10.2925444361668" y="456.227279278352" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>