<Workspace Version="1.2.1.3083" X="70.8716269263222" Y="77.2956582181656" zoom="0.658674852158215" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="0b893fc1-e7ad-4ffe-9c9b-e5079a91ed73" type="PythonNodeModels.PythonNode" nickname="Python Script" x="122.308409262189" y="83.9549939064547" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

import sys
pyt_path = r"C:\Program Files (x86)\IronPython 2.7\Lib"
sys.path.append(pyt_path)
import os

imagePath = r"C:\Users\sgaray\Desktop"
#imagename = "slice141.png"
#sys.path.append(imagePath)

os.system("python invertImages.py imagePath imageName")


# some code here

#pid = subprocess.Popen([sys.executable, "longtask.py"])

#Assign your output to the OUT variable.
</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>